export default [
  {
    company: {
      name: "Amazon",
      logo: "https://img.icons8.com/color/512/amazon.png",
    },
    profile:"Full stack developer",
    contract: "Full time",
    location:"USA",
    postDay: 3,
    isFeatured: true,
    tags: ["Senior", "HTML", "CSS", "Javascript", "Remote", "Full-time"],
  },
  {
    company: {
      name: "Google",
      logo: "https://img.icons8.com/color/512/google-logo.png",
    },
    profile:"Frontend developer",
    contract: "Full time",
    location:"Remote",
    postDay: 1,
    isFeatured: false,
    tags: ["Junior", "HTML", "CSS", "Part-time","Vue"],
  },
  {
    company: {
      name: "Meta",
      logo: "https://img.icons8.com/fluency/512/meta.png",
    },
    profile:"System engineer",
    contract: "Full time",
    location:"Netherlands",
    postDay: 3,
    isFeatured: false,
    tags: ["React","Sass","Javascript","Frontend","Junior"],
  },
  {
    company: {
      name: "PayTM",
      logo: "https://img.icons8.com/color/512/paytm.png",
    },
    profile:"Frontend engineer",
    contract: "Full time",
    location:"UK only",
    postDay: 1,
    isFeatured: false,
    tags: ["Senior","Contract","Remote","CSS","Angular","Javascript","Vue"],
  },
  {
    company: {
      name: "Spotify",
      logo: "https://img.icons8.com/fluency/512/spotify.png",
    },
    profile:"Backend engineer",
    contract: "Remote",
    location:"Netherlands",
    postDay: 5,
    isFeatured: true,
    tags: ["Mid-level","Fullstack","Ruby","Javascript","CSS"],
  },
  {
    company: {
      name: "Uber Eats",
      logo: "https://img.icons8.com/color/512/uber-eats-app.png",
    },
    profile:"Fullstack developer",
    contract: "Remote",
    location:"USA",
    postDay: 2,
    isFeatured: true,
    tags: ["Python","Django","React","Sass","Fullstack"],
  },
  {
    company: {
      name: "Uber",
      logo: "https://img.icons8.com/color/512/uber-app.png",
    },
    profile:"Junior frontend engineer",
    contract: "Remote",
    location:"Netherlands",
    postDay: 4,
    isFeatured: false,
    tags: ["Junior","HTML","Sass","CSS","Tailwind CSS","Angular","Javascript"],
  },
];
